#!/bin/sh

export LANG=C
export LC_ALL=C

list="/etc/apt/sources.list.d/omv-extras-org.list"

if [ -f "${list}" ]; then
  sed -i "s/jessie/stretch/g" ${list}
  sed -i "s/erasmus/arrakis/g" ${list}
fi

exit 0
