#!/bin/sh

export LANG=C
export LC_ALL=C

armbian="/etc/apt/sources.list.d/armbian.list"
docker="/etc/apt/sources.list.d/omvdocker.list"
list="/etc/apt/sources.list.d/omvextras.list"
pref="/etc/apt/preferences.d/omvextras.pref"
pve="/etc/apt/sources.list.d/pvekernel.list"

if [ -f "${armbian}" ]; then
  echo "Fixing Armbian repo ..."
  sed -i "s/bullseye/bookworm/g" ${armbian}
fi

if [ -f "${docker}" ]; then
  echo "Fixing Docker repo ..."
  sed -i "s/bullseye/bookworm/g" ${docker}
fi

if [ -f "${list}" ]; then
  echo "Fixing omv-extras repos ..."
  sed -i "/-testing/d" ${list}
  sed -i "/-extras/d" ${list}
  sed -i "s/bullseye/bookworm/g" ${list}
  sed -i "s/shaitan/sandworm/g" ${list}
fi

if [ -f "${pref}" ]; then
  echo "Fixing omv-extras pinnings ..."
  sed -i "s/bullseye/bookworm/g" ${pref}
fi

if [ -f "${pve}" ]; then
  echo "Fixing Proxmox repo ..."
  sed -i "s/bullseye/bookworm/g" ${pve}
fi

exit 0
