#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMVEXTRASREPOFILE="/etc/apt/sources.list.d/omv-extras-org.list"
KEYSERVER="hkp://keyserver.ubuntu.com:80"
XPATH="/config/system/omvextras/repos/repo"

ISO_PATH="/boot"
GRUB_CLONEZILLA="/etc/grub.d/42_clonezilla"
CLONEZILLA_VERSION="2.3.2-22"
CLONEZILLA_ISO="clonezilla-live-${CLONEZILLA_VERSION}-i686-pae.iso"

GRUB_SYSRESCCD="/etc/grub.d/42_sysresccd"
SYSRESCCD_VERSION="4.9.2"
SYSRESCCD_ISO="systemrescuecd-x86-${SYSRESCCD_VERSION}.iso"

GRUB_GPARTEDLIVE="/etc/grub.d/42_gpartedlive"
GPARTEDLIVE_VERSION="0.27.0-1"
GPARTEDLIVE_ISO="gparted-live-${GPARTEDLIVE_VERSION}-i686.iso"

GRUB="/etc/default/grub"
GRUB_BACKUP="grub.bak"
GRUB_CFG="/boot/grub/grub.cfg"
TFILE="/tmp/grub"

if [ "$1" == "omvextras" ] || [ "$1" == "mkconf" ]; then
    shift
fi

update()
{
    export LANG=C
    export LC_ALL=C

    OMVEXTRASAPTPREFS="/etc/apt/preferences.d/99omv-extras-org"

    /bin/rm -f ${OMVEXTRASREPOFILE}
    /bin/rm -f ${OMVEXTRASAPTPREFS}
    /bin/rm -f /etc/apt/sources.list.d/omv-extras-org*.list

    cat <<EOF > ${OMVEXTRASAPTPREFS}
Package: *
Pin: release n=erasmus-backports, origin dl.bintray.com
Pin-Priority: 995

Package: virtualbox virtualbox-dkms virtualbox-qt minidlna borgbackup python3-msgpack
  certbot python-acme python-certbot python-cffi python-cffi-backend python-chardet
  python-configargparse python-configobj python-cryptography python-dialog python-enum34
  python-funcsigs python-idna python-ipaddress python-mock python-ndg-httpsclient
  python-openssl python-parsedatetime python-pbr python-pkg-resources python-psutil
  python-pyasn1 python-requests python-rfc3339 python-setuptools python-six python-tz
  python-urllib3 python-zope.component python-zope.event python-zope.interface dkms
Pin: release a=jessie-backports
Pin-Priority: 500

EOF

    # Process repos
    echo "# This is file is generated." > ${OMVEXTRASREPOFILE}
    echo "# OMV-Extras repos" >> ${OMVEXTRASREPOFILE}

    count=$(omv_config_get_count "${XPATH}")
    index=0
    while [ ${index} -le ${count} ]; do
        enable=$(omv_config_get "${XPATH}[position()=${index}]/enable")
        name=$(omv_config_get "${XPATH}[position()=${index}]/name")

        if [ "${enable}" != "0" ]; then
            echo "# ${name}" >> ${OMVEXTRASREPOFILE}

            for i in $(seq 1 3); do
                repo=$(omv_config_get "${XPATH}[position()=${index}]/repo${i}")
                if [ "${repo}" != "" ]; then
                    key=$(omv_config_get "${XPATH}[position()=${index}]/key${i}")

                    if [[ ${repo} == deb* ]]; then
                        repopart=$(echo ${repo} | awk '{print $2 " " $3}')
                    else
                        repopart=$(echo ${repo} | awk '{print $1 " " $2}')
                    fi
                    if ! grep -lq "^[^#].*${repopart}" /etc/apt/sources.list.d/*.list; then
                        if [[ ${repo} == deb* ]]; then
                            echo "${repo}" >> ${OMVEXTRASREPOFILE}
                        else
                            echo "deb ${repo}" >> ${OMVEXTRASREPOFILE}
                        fi

                        if [ "${key}" != "" ]; then
                            key=${key,,}
                            if [ ${key:0:4} = "http" ]; then
                                wget -qO - "${key}" -4 2>/dev/null | apt-key add -
                            else
                                apt-key adv --keyserver ${KEYSERVER} --recv-keys "${key}"
                            fi
                        fi

                        package=$(omv_config_get "${XPATH}[position()=${index}]/package${i}")
                        pin=$(omv_config_get "${XPATH}[position()=${index}]/pin${i}")
                        priority=$(omv_config_get "${XPATH}[position()=${index}]/priority${i}")

                        if [ "${package}" != "" ]; then
                            echo "Package: ${package}" >> ${OMVEXTRASAPTPREFS}
                            echo "Pin: ${pin}" >> ${OMVEXTRASAPTPREFS}
                            echo "Pin-Priority: ${priority}" >> ${OMVEXTRASAPTPREFS}
                            echo "" >> ${OMVEXTRASAPTPREFS}
                        fi
                    else
                        echo "# repo already exists in another .list file" >> ${OMVEXTRASREPOFILE}
                    fi
                fi
            done
        fi

        index=$(( ${index} + 1 ))
    done

    chmod 644 ${OMVEXTRASAPTPREFS}
}

pvekernel()
{
    export LANG=C
    export DEBIAN_FRONTEND=noninteractive

    case "$(/usr/bin/arch)" in
        *amd64*|*x86_64*)

            pverepo="/etc/apt/sources.list.d/pvekernel.list"
            echo "deb http://download.proxmox.com/debian jessie pve-no-subscription" > ${pverepo}

            echo "Adding Proxmox repo key..."
            apt-key adv --keyserver ${KEYSERVER} --recv "C23AC7F49887F95A"

            echo "Updating..."
            apt-get update

            kernel=$(apt-cache search pve-kernel-4 | sort --version-sort | tail -n1 | cut -d" " -f1)

            if [ "${kernel}" != "" ]; then
                echo "Install Proxmox kernel and headers"
                if dpkg -l | grep firmware-ti-connectivity; then
                    apt-get --yes --force-yes purge firmware-ti-connectivity firmware-amd-graphics
                fi
                if dpkg -l | grep firmware-amd-graphics; then
                    apt-get --yes --force-yes purge firmware-amd-graphics
                fi
                apt-get --yes --force-yes --fix-missing install ${kernel} pve-headers pve-firmware
            else
                echo "No Proxmox kernel found."
            fi

            disablesubmenu

            echo "Removing Proxmox repo to prevent other packages from being updated..."
            rm -f ${pverepo}
            apt-get update

            echo "..."
            echo "Please reboot to use new kernel"
            ;;
        *)
            echo "Unsupported kernel and/or processor"
            ;;
    esac
}

installclonezilla()
{
    echo "Installing Clonezilla..."
    if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
        rm -f ${ISO_PATH}/clonezilla*.iso
        wget "https://downloads.sourceforge.net/project/clonezilla/clonezilla_live_stable/${CLONEZILLA_VERSION}/${CLONEZILLA_ISO}" -O ${ISO_PATH}/${CLONEZILLA_ISO} 2>&1
    fi

    cat <<EOF > ${GRUB_CLONEZILLA}
#!/bin/sh
exec tail -n +3 \$0
menuentry 'Clonezilla Live' {
  set isofile="${ISO_PATH}/${CLONEZILLA_ISO}"
  loopback loop \$isofile
  linux (loop)/live/vmlinuz boot=live live-config noswap nolocales edd=on nomodeset ocs_live_run="ocs-live-general" ocs_live_extra_param="" keyboard-layouts="" ocs_live_batch="no" locales="" ocs_daemonon="ssh" vga=788 nosplash toram=filesystem.squashfs findiso=\$isofile
  initrd (loop)/live/initrd.img
}
EOF

    chmod 755 ${GRUB_CLONEZILLA}
    update-grub
}

installsysresccd()
{
    if [ ! -f "${ISO_PATH}/${SYSRESCCD_ISO}" ]; then
        rm -f ${ISO_PATH}/systemrescuecd*.iso
        wget "https://sourceforge.net/projects/systemrescuecd/files/sysresccd-x86/${SYSRESCCD_VERSION}/${SYSRESCCD_ISO}/download" -O ${ISO_PATH}/${SYSRESCCD_ISO} 2>&1
    fi

    ARCH="$(bin/uname -m)"
    case "$ARCH" in
        x86_64)
            rescue="64"
        ;;
        *)
            rescue="32"
        ;;
    esac

    cat <<EOF > ${GRUB_SYSRESCCD}
#!/bin/sh
exec tail -n +3 \$0
menuentry 'SystemRescueCD' {
  set isofile="${ISO_PATH}/${SYSRESCCD_ISO}"
  loopback loop \$isofile
  linux (loop)/isolinux/rescue${rescue} nomodeset setkmap=us rootpass=openmediavault docache isoloop=\$isofile
  initrd (loop)/isolinux/initram.igz
}
EOF

    chmod 755 ${GRUB_SYSRESCCD}
    update-grub
}

installgpartedlive()
{
    if [ ! -f "${ISO_PATH}/${GPARTEDLIVE_ISO}" ]; then
        rm -f ${ISO_PATH}/gparted-live*.iso
        wget "https://downloads.sourceforge.net/gparted/${GPARTEDLIVE_ISO}" -O ${ISO_PATH}/${GPARTEDLIVE_ISO} 2>&1
    fi

    cat <<EOF > ${GRUB_GPARTEDLIVE}
#!/bin/sh
exec tail -n +3 \$0
menuentry 'GParted Live' {
  set isofile="${ISO_PATH}/${GPARTEDLIVE_ISO}"
  loopback loop \$isofile
  linux (loop)/live/vmlinuz boot='live' union='overlay' username='user' config components noswap noeject toram='filesystem.squashfs' ip='' nosplash findiso=\$isofile
  initrd (loop)/live/initrd.img
}
EOF

    chmod 755 ${GRUB_GPARTEDLIVE}
    update-grub
}

rebootclonezilla()
{
    if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
        echo "Please click on Install button."
    else
        DEFAULT=$(cat ${GRUB} | grep GRUB_DEFAULT | cut -d= -f2)

        disablesubmenu

        if grep -q 'submenu' ${GRUB_CFG}; then
            ENTRY=$(cat ${GRUB_CFG} | grep '^menuentry ' | grep -n Clonezilla | cut -f1 -d:)
        else
            ENTRY=$(($(cat ${GRUB_CFG} | grep 'menuentry ' | grep -n Clonezilla | cut -f1 -d:)-1))
        fi

        echo "Configuring grub to boot once from Clonezilla iso...  ${ENTRY}"

        perl -p -i -e "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/g" ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

rebootsysresccd()
{
    if [ ! -f "${ISO_PATH}/${SYSRESCCD_ISO}" ]; then
        echo "Please click on Install button."
    else
        DEFAULT=$(cat ${GRUB} | grep GRUB_DEFAULT | cut -d= -f2)

        disablesubmenu

        if grep -q 'submenu' ${GRUB_CFG}; then
            ENTRY=$(cat ${GRUB_CFG} | grep '^menuentry ' | grep -n SystemRescueCD | cut -f1 -d:)
        else
            ENTRY=$(($(cat ${GRUB_CFG} | grep 'menuentry ' | grep -n SystemRescueCD | cut -f1 -d:)-1))
        fi

        echo "Configuring grub to boot once from SystemRescueCD iso...  ${ENTRY}"

        perl -p -i -e "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/g" ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

rebootgpartedlive()
{
    if [ ! -f "${ISO_PATH}/${GPARTEDLIVE_ISO}" ]; then
        echo "Please click on Install button."
    else
        DEFAULT=$(cat ${GRUB} | grep GRUB_DEFAULT | cut -d= -f2)

        disablesubmenu

        if grep -q 'submenu' ${GRUB_CFG}; then
            ENTRY=$(cat ${GRUB_CFG} | grep '^menuentry ' | grep -n GParted | cut -f1 -d:)
        else
            ENTRY=$(($(cat ${GRUB_CFG} | grep 'menuentry ' | grep -n GParted | cut -f1 -d:)-1))
        fi

        echo "Configuring grub to boot once from GParted Live iso...  ${ENTRY}"

        perl -p -i -e "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/g" ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

disablesubmenu()
{
    if ! grep -q 'GRUB_DISABLE_SUBMENU' ${GRUB}; then
        echo "GRUB_DISABLE_SUBMENU=y" >> ${GRUB}
        update-grub
    fi
}

case $1 in
    update)
        update
    ;;

    aptclean)
        update
        /usr/sbin/omv-aptclean
    ;;

    installpvekernel)
        pvekernel
    ;;

    disablesubmenu)
        disablesubmenu
    ;;

    installcz)
        installclonezilla
    ;;

    installgp)
        installgpartedlive
    ;;

    installsys)
        installsysresccd
    ;;

    rebootcz)
        rebootclonezilla
    ;;

    rebootgp)
        rebootgpartedlive
    ;;

    rebootsys)
        rebootsysresccd
    ;;

    configure)
        update
    ;;

    *)
        update
        apt-get update || :
    ;;
esac

exit 0
