#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    openmediavault-developers
# @copyright Copyright (c) 2009-2014 openmediavault-developers
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /usr/share/openmediavault/sysinfo/functions

HWRAID_BIN="/usr/sbin/hpacucli"

if [ ! -f "${HWRAID_BIN}" ]; then
    exit 0
fi

omv_sysinfo_begin_msg "HP Hardware RAID"

DETECT_CONTROLLERS="$($HWRAID_BIN ctrl all show &>1 | sed -e '/^\s*$/d')"

REGEX=".*No controllers detected"
if [ "$(echo $DETECT_CONTROLLERS | grep 'No controllers detected')" ]; then
    echo "$DETECT_CONTROLLERS" | sed 's/Error: //g'
fi

#SLOTLIST=$($HWRAID_BIN ctrl all show | \
#  grep Slot | sed -e 's/^.*Slot //g' -e 's/ .*$//g')
SLOTLIST=$(echo "$DETECT_CONTROLLERS" | \
  grep Slot | sed -e 's/^.*Slot //g' -e 's/ .*$//g')

for SLOTNR in $SLOTLIST; do
    omv_sysinfo_msg ""
    omv_sysinfo_msg "CONTROLLER INFO:"
    omv_sysinfo_msg_separator
    $HWRAID_BIN ctrl slot=$SLOTNR show | grep -v "^$"  | omv_sysinfo_msg
    omv_sysinfo_msg ""
    omv_sysinfo_msg ""
    omv_sysinfo_msg "CONTROLLER STATUS:"
    omv_sysinfo_msg_separator
    $HWRAID_BIN ctrl slot=$SLOTNR show status | grep -v "^$"  | omv_sysinfo_msg
    omv_sysinfo_msg ""
    omv_sysinfo_msg ""
    omv_sysinfo_msg "LOGICAL DRIVE INFO:"
    omv_sysinfo_msg_separator
    $HWRAID_BIN ctrl slot=$SLOTNR ld all show | grep -v "^$"  | omv_sysinfo_msg
    omv_sysinfo_msg ""
    omv_sysinfo_msg ""
    omv_sysinfo_msg "PHYSICAL DRIVE INFO:"
    omv_sysinfo_msg_separator
    $HWRAID_BIN ctrl slot=$SLOTNR pd all show | grep -v "^$" | omv_sysinfo_msg
    omv_sysinfo_msg ""
    omv_sysinfo_msg ""
    omv_sysinfo_msg "PHYSICAL DRIVE STATUS:"
    omv_sysinfo_msg_separator
    $HWRAID_BIN ctrl slot=$SLOTNR pd all show detail | \
      grep -i -P '.*(physicaldrive|Firmware|Status|Temperature|Interface|Size|Serial|Speed|Transfer|Model).*'  | omv_sysinfo_msg
    omv_sysinfo_msg ""
done

omv_sysinfo_end_msg

exit 0
