#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Aaron Murray <aaron@omv-extras.org>
#           Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c)  2013-2014 Aaron Murray
#                           2011-2012 Marcel Beck
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_UPGRADE_SCRIPTS_DIR=${OMV_UPGRADE_SCRIPTS_DIR:-"/usr/share/openmediavault/releaseupgrade"}
OMVEXTRAS_PRE_UNLOCK_SCRIPT=${OMV_UPGRADE_SCRIPTS_DIR}/pre.d/19-unlock-apt-sources
OMVEXTRAS_PRE_UPGRADE_SCRIPT=${OMV_UPGRADE_SCRIPTS_DIR}/pre.d/21-update-omvextrasorg

if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then

    # Remove the configuration data
    omv_config_delete "/config/system/omvextrasorg"

    /bin/rm -f /etc/apt/preferences.d/99omv-extras-org*
    /bin/rm -f /etc/apt/sources.list.d/omv-extras-org-*.list

    if [ -f ${OMVEXTRAS_PRE_UNLOCK_SCRIPT} ]; then
        /bin/rm -f ${OMVEXTRAS_PRE_UNLOCK_SCRIPT}
    fi

    if [ -f ${OMVEXTRAS_PRE_UPGRADE_SCRIPT} ]; then
        /bin/rm -f ${OMVEXTRAS_PRE_UPGRADE_SCRIPT}
    fi
fi

exit 0
