#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Aaron Murray <aaron@omv-extras.org>
#           Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c)  2013-2014 Aaron Murray
#                           2011-2012 Marcel Beck
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)

        if ! omv_config_exists "/config/system/omvextrasorg"; then
            echo "Initialize configuration"
            object="<enable>1</enable>"
            object="${object}<testing>0</testing>"
            object="${object}<developer>n/a</developer>"
            object="${object}<vbox>0</vbox>"
            object="${object}<plex>0</plex>"
            object="${object}<greyhole>0</greyhole>"
            object="${object}<vdr>0</vdr>"
            object="${object}<miller>0</miller>"
            object="${object}<millertesting>0</millertesting>"
            object="${object}<btsync>0</btsync>"
            object="${object}<beta>0</beta>"
            object="${object}<dotdeb>0</dotdeb>"
            object="${object}<debmm>0</debmm>"
            object="${object}<debmmbp>0</debmmbp>"
            omv_config_add_element "/config/system" "omvextrasorg" "${object}" true
        fi

        if ! omv_config_exists "/config/system/omvextrasorg/repos"; then
            omv_config_add_element "/config/system/omvextrasorg" "repos" ""
        fi

        omv-mkconf omvextrasorg

        if [ -x /usr/bin/apt-key ]; then
            apt-key add /usr/share/keyrings/omvextrasorg-keyring.gpg
            apt-key add /usr/share/keyrings/oracle_vbox.asc
            apt-key add /usr/share/keyrings/shell-ninthgate-se-keyring.key
            apt-key add /usr/share/keyrings/dotdeb.gpg
            apt-key add /usr/share/keyrings/deb-multimedia-keyring.gpg
            apt-key add /usr/share/keyrings/greyhole-debsig.asc
            apt-key add /usr/share/keyrings/e-tobi-keyring.gpg
            apt-key add /usr/share/keyrings/btsync.gpg
        fi

        chattr +i /etc/apt/sources.list
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
