#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2013-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if ! omv_config_exists "/config/system/omvextras"; then
            echo "Initialize configuration"
            default_repos=$(cat /etc/omvextras/default_repos.xml | sed -e 's/^[ \t]*//' | tr '\n' ' ')
            omv_config_add_node_data "/config/system" "omvextras" "${default_repos}"
        fi

        if dpkg --compare-versions "$2" lt-nl "3.4"; then
            rm -f /etc/apt/sources.list.d/backports.list
            update_repo=$(cat /etc/omvextras/update1.xml | sed -e 's/^[ \t]*//' | tr '\n' ' ')
            omv_config_add_node_data "/config/system/omvextras/repos" "repo" "${update_repo}"
        fi

        if [ ! -f /usr/share/openmediavault/mkconf/omvextrasorg ]; then
            ln -s /usr/share/openmediavault/mkconf/omvextras /usr/share/openmediavault/mkconf/omvextrasorg
        fi

        omv-mkconf omvextras update

        if [ -x /usr/bin/apt-key ]; then
            KEYRING_LOCATION="/usr/share/keyrings/"
            apt-key add ${KEYRING_LOCATION}omvextrasorg-keyring.gpg
            apt-key add ${KEYRING_LOCATION}omvplugindevs.gpg
            apt-key add ${KEYRING_LOCATION}omvextrasdevs.key
            apt-key add ${KEYRING_LOCATION}greyhole-debsig.asc
            apt-key add ${KEYRING_LOCATION}zfsonlinux.gpg
            apt-key add ${KEYRING_LOCATION}xamarin.gpg
            apt-key add ${KEYRING_LOCATION}deluge.key
            apt-key add ${KEYRING_LOCATION}hwraid.le-vert.net.gpg.key
            apt-key add ${KEYRING_LOCATION}docker.gpg
            apt-key add ${KEYRING_LOCATION}syncthing.key
        fi

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
