#!/bin/bash

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

status=$1

# remove backports from sources.list if found
sed -i "/$(lsb_release -sc)-backports/d" /etc/apt/sources.list

if omv_checkyesno ${status}; then
  echo "Enabling backports..."
  bp="YES"
else
  echo "Disabling backports..."
  bp="NO"
fi
omv_set_default "OMV_APT_USE_KERNEL_BACKPORTS" "${bp}" true
omv-salt stage run --quiet prepare
omv-salt deploy run apt
omv-aptclean repos

exit 0
