#!/bin/bash

if [ "$UID" -ne "0" ]; then
  echo "Must be run as root."
  exit 1
fi

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

XPATH="/config/system/omvextras/repos/repo"

show()
{
  count=$(omv_config_get_count "${XPATH}")
  index=1
  while [ ${index} -le ${count} ]; do
    enable=$(omv_config_get "${XPATH}[position()=${index}]/enable")
    name=$(omv_config_get "${XPATH}[position()=${index}]/name")
    echo "${name} = ${enable}"
    index=$(( ${index} + 1 ))
  done
}

if [ -z "${1}" ]; then
  echo "Usage:  omv-changerepo 'OMV-Extras.org' enable"
  echo "Usage:  omv-changerepo 'OMV-Extras.org' disable"
  echo ""
  echo "Current values:"
  echo "==================================="
  show

  exit 0
fi

echo "Previous values:"
echo "==================================="
show

if [ "${2}" = "disable" ]; then
  value=0
else
  value=1
fi

cp ${OMV_CONFIG_FILE} /root/
xmlstarlet ed -L -u "${XPATH}[name='${1}']/enable" -v ${value} ${OMV_CONFIG_FILE}

echo ""
echo "Current values:"
echo "==================================="
show

echo ""
echo "Now execute:  apt-get update"
echo ""
