#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2020 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

arch="$(dpkg --print-architecture)"

if [[ "${arch}" == "amd64" ]]; then
  isoArch="amd64"
elif [[ "${arch}" == "i386" ]]; then
  isoArch="i686"
else
  echo "Unsupported architecture."
  exit 0
fi

ISO_PATH="/boot"
GRUB_CLONEZILLA="/etc/grub.d/42_clonezilla"
CLONEZILLA_VERSION="2.6.0-37"
CLONEZILLA_ISO="clonezilla-live-${CLONEZILLA_VERSION}-i686-pae.iso"

GRUB_SYSRESCCD="/etc/grub.d/42_sysresccd"
SYSRESCCD_VERSION="6.1.1"
SYSRESCCD_ISO="systemrescuecd-${isoArch}-${SYSRESCCD_VERSION}.iso"

GRUB_GPARTEDLIVE="/etc/grub.d/42_gpartedlive"
GPARTEDLIVE_VERSION="1.1.0-1"
GPARTEDLIVE_ISO="gparted-live-${GPARTEDLIVE_VERSION}-${isoArch}.iso"

GRUB="/etc/default/grub"
GRUB_CFG="/boot/grub/grub.cfg"

checkDNS()
{
  host="/usr/bin/host"
  if [ -f "${host}" ]; then
    if ! ${host} sourceforge.net > /dev/null; then
      echo "DNS error.  Exiting ..."
      exit 0
    else
      echo "DNS OK."
    fi
  fi
}

installclonezilla()
{
    checkDNS

    echo "Installing Clonezilla..."
    if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
        rm -f ${ISO_PATH}/clonezilla*.iso
        wget "https://downloads.sourceforge.net/project/clonezilla/clonezilla_live_stable/${CLONEZILLA_VERSION}/${CLONEZILLA_ISO}" -O ${ISO_PATH}/${CLONEZILLA_ISO} 2>&1
    else
        echo "${CLONEZILLA_ISO} already exists.  Skipping download."
    fi
    echo "Creating GRUB entry..."
    cat <<EOF > ${GRUB_CLONEZILLA}
#!/bin/sh
exec tail -n +3 \$0
menuentry 'Clonezilla Live' {
  set isofile="${ISO_PATH}/${CLONEZILLA_ISO}"
  loopback loop \$isofile
  linux (loop)/live/vmlinuz boot=live live-config noswap edd=on nomodeset ocs_prerun="dhclient" ocs_live_run="ocs-live-general" ocs_live_extra_param="" keyboard-layouts=NONE ocs_live_batch="no" locales="en_US.UTF-8" ocs_daemonon="ssh" vga=788 nosplash toram=filesystem.squashfs findiso=\$isofile
  initrd (loop)/live/initrd.img
}
EOF

    chmod 755 ${GRUB_CLONEZILLA}
    update-grub
}

installsysresccd()
{
    checkDNS

    if [ ! -f "${ISO_PATH}/${SYSRESCCD_ISO}" ]; then
        rm -f ${ISO_PATH}/systemrescuecd*.iso
        wget "https://osdn.net/projects/systemrescuecd/storage/releases/${SYSRESCCD_VERSION}/${SYSRESCCD_ISO}" -O ${ISO_PATH}/${SYSRESCCD_ISO} 2>&1
    else
        echo "${SYSRESCCD_ISO} already exists.  Skipping download."
    fi
    echo "Creating GRUB entry..."
    cat <<EOF > ${GRUB_SYSRESCCD}
#!/bin/sh
exec tail -n +3 \$0
menuentry 'SystemRescueCD' {
  probe -u \$root --set=rootuuid
  set imgdevpath="/dev/disk/by-uuid/\$rootuuid"
  set isofile="${ISO_PATH}/${SYSRESCCD_ISO}"
  loopback loop \$isofile
  linux (loop)/sysresccd/boot/x86_64/vmlinuz rootpass=openmediavault nomodeset nofirewall archisobasedir=sysresccd copytoram setkmap=us img_dev=\$imgdevpath img_loop=\$isofile earlymodules=loop
  initrd (loop)/sysresccd/boot/intel_ucode.img (loop)/sysresccd/boot/amd_ucode.img (loop)/sysresccd/boot/x86_64/sysresccd.img
}
EOF
    chmod 755 ${GRUB_SYSRESCCD}
    update-grub
}

installgpartedlive()
{
    checkDNS

    if [ ! -f "${ISO_PATH}/${GPARTEDLIVE_ISO}" ]; then
        rm -f ${ISO_PATH}/gparted-live*.iso
        wget "https://downloads.sourceforge.net/gparted/${GPARTEDLIVE_ISO}" -O ${ISO_PATH}/${GPARTEDLIVE_ISO} 2>&1
    else
        echo "${GPARTEDLIVE_ISO} already exists.  Skipping download."
    fi
    echo "Creating GRUB entry..."
    cat <<EOF > ${GRUB_GPARTEDLIVE}
#!/bin/sh
exec tail -n +3 \$0
menuentry 'GParted Live' {
  set isofile="${ISO_PATH}/${GPARTEDLIVE_ISO}"
  loopback loop \$isofile
  linux (loop)/live/vmlinuz boot='live' union='overlay' username='user' config components noswap noeject toram='filesystem.squashfs' ip='' nosplash findiso=\$isofile
  initrd (loop)/live/initrd.img
}
EOF

    chmod 755 ${GRUB_GPARTEDLIVE}
    update-grub
}

rebootclonezilla()
{
    if [ ! -f "${ISO_PATH}/${CLONEZILLA_ISO}" ]; then
        echo "Please click on Install button."
    else
        DEFAULT=$(awk -F "=" '$1 == "GRUB_DEFAULT" { print $2 }' ${GRUB})

        disablesubmenu

        if grep -q 'submenu' ${GRUB_CFG}; then
            ENTRY=$(grep '^menuentry ' ${GRUB_CFG} | grep -n Clonezilla | cut -f1 -d:)
        else
            ENTRY=$(($(grep 'menuentry ' ${GRUB_CFG} | grep -n Clonezilla | cut -f1 -d:)-1))
        fi

        echo "Configuring grub to boot once from Clonezilla iso...  ${ENTRY}"

        perl -p -i -e "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/g" ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

rebootsysresccd()
{
    if [ ! -f "${ISO_PATH}/${SYSRESCCD_ISO}" ]; then
        echo "Please click on Install button."
    else
        DEFAULT=$(awk -F "=" '$1 == "GRUB_DEFAULT" { print $2 }' ${GRUB})

        disablesubmenu

        if grep -q 'submenu' ${GRUB_CFG}; then
            ENTRY=$(grep '^menuentry ' ${GRUB_CFG} | grep -n SystemRescueCD | cut -f1 -d:)
        else
            ENTRY=$(($(grep 'menuentry ' ${GRUB_CFG} | grep -n SystemRescueCD | cut -f1 -d:)-1))
        fi

        echo "Configuring grub to boot once from SystemRescueCD iso...  ${ENTRY}"

        perl -p -i -e "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/g" ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

rebootgpartedlive()
{
    if [ ! -f "${ISO_PATH}/${GPARTEDLIVE_ISO}" ]; then
        echo "Please click on Install button."
    else
        DEFAULT=$(awk -F "=" '$1 == "GRUB_DEFAULT" { print $2 }' ${GRUB})

        disablesubmenu

        if grep -q 'submenu' ${GRUB_CFG}; then
            ENTRY=$(grep '^menuentry ' ${GRUB_CFG} | grep -n GParted | cut -f1 -d:)
        else
            ENTRY=$(($(grep 'menuentry ' ${GRUB_CFG} | grep -n GParted | cut -f1 -d:)-1))
        fi

        echo "Configuring grub to boot once from GParted Live iso...  ${ENTRY}"

        perl -p -i -e "s/GRUB_DEFAULT=.*/GRUB_DEFAULT=saved/g" ${GRUB}
        grub-set-default ${DEFAULT}
        update-grub
        grub-reboot ${ENTRY}
    fi
}

disablesubmenu()
{
    if ! grep -q 'GRUB_DISABLE_SUBMENU' ${GRUB}; then
        echo "GRUB_DISABLE_SUBMENU=y" >> ${GRUB}
        update-grub
    fi
}

case $1 in
    disablesubmenu)
        disablesubmenu
    ;;

    installcz)
        installclonezilla
    ;;

    installgp)
        installgpartedlive
    ;;

    installsys)
        installsysresccd
    ;;

    rebootcz)
        rebootclonezilla
    ;;

    rebootgp)
        rebootgpartedlive
    ;;

    rebootsys)
        rebootsysresccd
    ;;
esac

exit 0
