#!/bin/sh

export LANG=C
export LC_ALL=C

if ! dpkg-query -W -f='${db:Status-Status}\n' openmediavault-flashmemory 2>/dev/null | grep -qx installed; then
  exit 0
fi

DEBIAN_FRONTEND=noninteractive apt-get -y purge folder2ram openmediavault-flashmemory
DEBIAN_FRONTEND=noninteractive apt-get -y install openmediavault-writecache
omv-salt deploy run writecache
