#!/bin/bash

# import the needed Libs
. /usr/local/bin/omv-support-libs

# Describe your Info-AddIn here
DESCRIPTION="Filesystem Info"

# Reads the filename
FILENAME="$1"

# Define the tmp-file on the filesystem
TMPFILE="$TMPFOLDER/$FILENAME"

f_log "##########################"
f_log "$FILENAME:"
f_log

# Begin of the script
f_log "fdisk -l"
f_log "--------------------------"
fdisk -l 2>&1 | tee -a $TMPFILE
f_log
f_log "df -h"
f_log "--------------------------"
df -h  2>&1 | tee -a $TMPFILE