#!/bin/bash

# import the needed Libs
. /usr/local/bin/omv-support-libs

# Describe your Info-AddIn here
DESCRIPTION="Information about free space"

# Reads the filename
FILENAME="$1"

# Define the tmp-file on the filesystem
TMPFILE="$TMPFOLDER/$FILENAME"

f_log "##########################"
f_log "$FILENAME:"
f_log

# Begin of the script

# test version from David:
# f_log "/var -> 10 largest files"
# f_log "--------------------------"
# du -hsx /* \
# --exclude=./media \
# --exclude=./dev \
# --exclude=./proc \
# --exclude=./lost+found \
# | sort -rh | head -10

f_log "/var -> 10 largest files"
f_log "--------------------------"
du -hsx /var/* | sort -rh | head -10 2>&1 | tee -a $TMPFILE
f_log "--------------------------"
f_log
f_log "/usr -> 10 largest files"
f_log "--------------------------"
du -hsx /usr/* | sort -rh | head -10 2>&1 | tee -a $TMPFILE