#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2018 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMVEXTRASREPOFILE="/etc/apt/sources.list.d/omv-extras-org.list"
KEYSERVER="hkp://keyserver.ubuntu.com:80"
XPATH="/config/system/omvextras/repos/repo"

OMVEXTRASAPTPREFS="/etc/apt/preferences.d/omv-extras-org"

rm -f ${OMVEXTRASAPTPREFS}

if ! omv_checkyesno "${OMV_APT_USE_KERNEL_BACKPORTS}"; then
    cat <<EOF > ${OMVEXTRASAPTPREFS}
Package: virtualbox*
Pin: release a=stretch-backports
Pin-Priority: 500

Package: zfs*
Pin: release a=stretch-backports
Pin-Priority: 500

Package: spl
Pin: release a=stretch-backports
Pin-Priority: 500

Package: spl-dkms
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libnvpair1linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libzfs2linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libzpool2linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: libuutil1linux
Pin: release a=stretch-backports
Pin-Priority: 500

Package: linux-compiler-gcc-6-x86
Pin: release a=stretch-backports
Pin-Priority: 500

Package: xrdp
Pin: release a=stretch-backports
Pin-Priority: 500

EOF
fi

# Process repos
echo "# This is file is generated." > ${OMVEXTRASREPOFILE}
echo "# OMV-Extras repos" >> ${OMVEXTRASREPOFILE}

count=$(omv_config_get_count "${XPATH}")
index=0
while [ ${index} -le ${count} ]; do
    enable=$(omv_config_get "${XPATH}[position()=${index}]/enable")
    name=$(omv_config_get "${XPATH}[position()=${index}]/name")

    if [ "${enable}" != "0" ]; then
        echo "# ${name}" >> ${OMVEXTRASREPOFILE}

        for i in $(seq 1 3); do
            repo=$(omv_config_get "${XPATH}[position()=${index}]/repo${i}")
            if [ "${repo}" != "" ]; then
                key=$(omv_config_get "${XPATH}[position()=${index}]/key${i}")

                if [[ ${repo} == deb* ]]; then
                    repopart=$(echo ${repo} | awk '{print $2 " " $3}')
                else
                    repopart=$(echo ${repo} | awk '{print $1 " " $2}')
                fi
                if ! grep -lq "^[^#].*${repopart}" /etc/apt/sources.list.d/*.list; then
                    if [[ ${repo} == deb* ]]; then
                        echo "${repo}" >> ${OMVEXTRASREPOFILE}
                    else
                        echo "deb ${repo}" >> ${OMVEXTRASREPOFILE}
                    fi

                    if [ "${key}" != "" ]; then
                        key=${key,,}
                        if [ ${key:0:4} = "http" ]; then
                            wget -qO - "${key}" -4 2>/dev/null | apt-key add -
                        else
                            apt-key adv --keyserver ${KEYSERVER} --recv-keys "${key}"
                        fi
                    fi

                    package=$(omv_config_get "${XPATH}[position()=${index}]/package${i}")
                    pin=$(omv_config_get "${XPATH}[position()=${index}]/pin${i}")
                    priority=$(omv_config_get "${XPATH}[position()=${index}]/priority${i}")

                    if [ "${package}" != "" ]; then
                        echo "Package: ${package}" >> ${OMVEXTRASAPTPREFS}
                        echo "Pin: ${pin}" >> ${OMVEXTRASAPTPREFS}
                        echo "Pin-Priority: ${priority}" >> ${OMVEXTRASAPTPREFS}
                        echo "" >> ${OMVEXTRASAPTPREFS}
                    fi
                else
                    echo "# repo already exists in another .list file" >> ${OMVEXTRASREPOFILE}
                fi
            fi
        done
    fi

    index=$(( ${index} + 1 ))
done

chmod 644 ${OMVEXTRASAPTPREFS}

exit 0
